### ISSUE TITLE
Suggestion - remove margin on mobile screen for cards

### ISSUE THREAD

**Issue by jzhu01** [joanneberina/capstone_colmar#5]
Seen here: https://github.com/joanneberina/capstone_colmar/blob/e791f66039414c401f78e565ee6e82a537e7c0f1/resources/css/styles.css#L332-L335

I understand you want to keep them for the hover effect, but on a mobile screen you can't really hover over an element like you do with a desktop. If anything I'd suggest decreasing it from 2rem to 0.5rem or something. :)

**Comment by joanneberina** [comment]
I removed the margin altogether thanks! :-)
